language: ruby
rvm:
  - 2.1.1
  - 1.9.3
before_script:
  - echo -e "test:\n  secret_key_base: " > config/secrets.yml
  - rake secret >> config/secrets.yml
  - bundle exec rake db:migrate
script:
  - bundle exec rspec
